kind: ApplicationAssignment
metadata:
  name: >-
    coral-applications-ApplicationRegistration-missionedge-appdev-sample-development-dev-airplane
spec:
  application:
    kind: ApplicationRegistration
    name: missionedge-appdev-sample
    workspace: coral-applications
    target: development
  cluster: dev-airplane
